print ("========Bienvenido a calculadora de puntaje final de jugador==========")
print ("Cada victoria vale 3 puntos y cada empate 1 punto")
Nombre = input("Ingrese el nombre del jugador: ")
Victorias = int(input("Ingrese el número de victorias: "))
Derrotas = int(input("Ingrese el número de derrotas: "))
empates = int(input("Ingrese el número de empates: "))
puntaje_final = (Victorias * 3) + (empates * 1)

print("\n===== RESULTADOS =====")
print("Jugador:", Nombre)
print("Victorias:", Victorias)
print("Empates:", empates)
print("Derrotas:", Derrotas)
print("Puntaje final:", puntaje_final)